// packages/react/src/QueryProvider.tsx
/* eslint-disable solid/no-destructure */
import { QueryClientProvider, type QueryClient } from '@tanstack/react-query'

const QueryProvider: React.FC<{
  children: React.ReactNode
  queryClient: QueryClient
}> = ({ children, queryClient }) => {
  return (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  )
}

export default QueryProvider

// packages/prpc/src/QueryProvider.tsx
import { QueryClient, QueryClientProvider } from "@adeora/solid-query";
import type { ParentComponent } from "solid-js";

export const QueryProvider: ParentComponent = (props) => {
  const queryClient = new QueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      {props.children}
    </QueryClientProvider>
  );
};
